defaults:
- _self_
- paths: default
- data: train1k_val20
- model: reprover_full_finetune
- ntp: default
- reward: default
- trainer: default

seed: 27
save_dir: runs

# values used across multiple config modules
shared_values:
  repeat_theorem_n_times: 1
  architecture: seq2seq # {seq2seq, causal}
  seq2seq: ${arch2seq2seq[${shared_values.architecture}]}
  use_4bit: false
  
# for variable interpolation
arch2seq2seq:
  seq2seq: true
  causal: false
