sft:
  data:
    splits: "random" # {random, novel_premises}
    train_size: 0.8
    include_next_state: false

    # paths are relative to the project root
    raw_data: "data/time_filtered.json"
    formatted_dataset_dir: "data/verifier_sft_dataset"

    
  