defaults:
  - _self_
  - task: five_theorems
  - device: gpu
  - hydra: default
  - paths: eddie

seed: 27
save_dir: "runs/"

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  # name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  # name: five_thm_effbatch256_run1
  name: max_batch_testing
  project: "gfn4ntp"
  save_dir: ${save_dir}
  offline: false
